server:
  port: 9060

eureka:
  instance:
    appname: feign-feign
    hostname: localhost
#    metadataMap.zone: zone-1
  client:
    registerWithEureka: true
    registry-fetch-interval-seconds: 2
    region: hangzhou
    serviceUrl:
      zone-1: http://localhost:9080/eureka/
      zone-2: http://xiaxi:9081/eureka/
    availability-zones.hangzhou: zone-1,zone-2