server:
  port: 9070

eureka:
  instance:
    hostname: localhost
    appname: feign-user
    virtual-host-name: feign-user
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9080/eureka/